import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Character, GetCharacterResults } from '../types/character';
import imageLoader from '../utils';

const Home: NextPage<{ characters: Character[] }> = ({ characters }: any) => {
	return (
		<div>
			<Head>
				<title className='w-100 mx-auto'>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{characters.map((character: Character) => (
				<div key={character.id}>
					<Link href={`/characters/${character.id}`}>
						<a>{character.name}</a>
					</Link>
					<Image
						loader={imageLoader}
						unoptimized
						src={character.image}
						alt={character.name}
						width='200'
						height='200'
					/>
				</div>
			))}
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const res = await fetch('https://rickandmortyapi.com/api/character');
	const { results }: GetCharacterResults = await res.json();

	return {
		props: {
			characters: results,
		},
	};
};

export default Home;
